import { strToU8, zipSync } from 'fflate';
import type { PartMesh } from '../geometry/build';
import { MATERIALS } from '../model/hardware';
import { toBinaryStl } from './stl';

/** Strip characters that are awkward in file names. */
function safeName(name: string): string {
  const s = name.trim().replace(/[\\/:*?"<>|]/g, '_');
  return s.length > 0 ? s : 'lamp';
}

/**
 * One zip containing a binary STL per part (`<name>-<partId>.stl`, print orientation applied,
 * min z = 0 on the bed) plus a README.txt listing material, mass, orientation and build notes.
 */
export function stlZip(parts: PartMesh[], name: string): Uint8Array {
  const base = safeName(name);
  const files: Record<string, Uint8Array> = {};
  const lines: string[] = [
    `${name} — printed parts (generated by Luz)`,
    '',
    'Units: millimetres. One binary STL per part, already rotated into print orientation',
    'and dropped onto the bed (min z = 0). Electrical parts are never printed.',
    '',
  ];
  for (const part of parts) {
    const file = `${base}-${part.id}.stl`;
    files[file] = toBinaryStl(part.mesh, part.printFlip, `${base} ${part.label}`);
    const mat = MATERIALS[part.material];
    lines.push(
      `${file} — ${part.label}`,
      `  material: ${mat.label} (HDT ${mat.hdt} °C; ${mat.source})`,
      `  approx. mass: ${part.mass.toFixed(0)} g (solid-model estimate; slicer infill will differ)`,
      `  print orientation: ${part.printFlip ? 'flipped 180° about X' : 'as modelled'}, resting on the bed`,
    );
    for (const note of part.notes) lines.push(`  note: ${note}`);
    lines.push('');
  }
  lines.push(
    'Use a cUL/CSA-listed cord set and socket; do not print any electrical part.',
    'These files and their checks are guidance, not a certification.',
  );
  files['README.txt'] = strToU8(lines.join('\n'));
  return zipSync(files, { level: 6 });
}
